import { View, Text ,Dimensions, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
    inputField:{
        borderRadius:10,
        borderColor:'#133863',
        marginVertical:10,
        color:'#091D34',
        backgroundColor:"#E1ECF9",
    },
    outlineStyle:{
        borderRadius:10,
        borderWidth:2,
    },
    inputFieldBox:{
        paddingVertical:10,
        width:'100%'
    },
    forgotPassword:{
        alignItems:'flex-end',
        paddingVertical:5
    },
    forgotPasswordText:{
        fontFamily:'BPdotsBold',
        fontSize:16,
        color:'#091D34'
    },
    errorMsg:{
        color:'#D01212',
    },
    fb_login:{
        backgroundColor:'#4867aa',
        justifyContent:'center',
        alignItems:'center',
        borderRadius:10,
        paddingVertical:15,
        margin:10,
        shadowColor:"#236AB9",
        shadowOffset:{
            width:0,
            height:10
        },
        shadowOpacity:0.25,
        shadowRadius:3.5,
        elevation:5,
        width:'100%'
    },
    g_login:{
        backgroundColor:'#f73e2f',
        justifyContent:'center',
        alignItems:'center',
        borderRadius:10,
        paddingVertical:15,
        marginBottom:10,
        shadowColor:"#f73e2f",
        shadowOffset:{
            width:0,
            height:10
        },
        shadowOpacity:0.25,
        shadowRadius:3.5,
        elevation:5,
        width:'100%'
    },
    orDevider:{
        height:2,
        backgroundColor:'#609CE1',
        marginVertical:15,
        width:'100%',
        justifyContent:'center',
        alignItems:'center'
    },
    orDeviderText:{
        color:'#091D34',
        position:'absolute',
        backgroundColor:'#E1ECF9',
        padding:3
    },
    signUpBox:{
        marginTop:25,
        flexDirection:'row',
    },
    newToSignUp:{
        color:'#091D34',
        fontFamily:"DotsAllForNow",
        fontSize:13
    },
    SignUpText:{
        color:'#236AB9',
        fontFamily:"DotsAllForNow",
        marginLeft:5,
        fontSize:13
    },
    
})